### ISSUE TITLE
nbsphinx fails on stripped notebooks

### ISSUE THREAD

**Issue by thvitt** [DARIAH-DE/Topics#14]
`jupyter nbconvert --execute` (which is run by `nbsphinx`) fails on our notebooks with:

```
Notebook error:
TypeError in Introducing_gensim.ipynb:
Undefined is not JSON serializable
```

The problem seems to go away when disabling the lines generating bokeh output. If this can be verified, disable #12 until we got rid of bokeh?

**Comment by thvitt** [comment]
I reproducably succeeded in running `jupyter nbconvert --to html --execute --allow-errors --ExecutePreprocessor.timeout=-1` on the notebooks which have been stripped of their output, while running the nbsphinx conversion on the clean notebooks fails with the error mentioned above.

There doesn't seem to be an nbsphinx option for more verbosity, probably need to run this under a debugger

**Comment by severinsimmler** [comment]
Bokeh will be replaced anyway wihtin the next week by mpld3.

**Comment by thvitt** [comment]
* nbsphinx seems to run fine on a Introducing_MALLET.ipynb after it has been opened in the browser, _Run all_, and saved.
* nbsphinx fails with the above-mentioned error both on stripped notebooks and on stripped notebooks that have added output information using `jupyter nbconvert --to notebook --execute`. 

So, something happens in the browser that does _not_ happen on headless execution.

**Comment by thvitt** [comment]
Here's the detailed exception

```
Notebook error:
TypeError in Introducing_MALLET.ipynb:
Traceback (most recent call last):
  File "/home/vitt/.virtualenvs/Topics/lib/python3.5/site-packages/nbsphinx.py", line 634, in parse
    rststring, resources = exporter.from_notebook_node(nb, resources)
  File "/home/vitt/.virtualenvs/Topics/lib/python3.5/site-packages/nbsphinx.py", line 582, in from_notebook_node
    nb, resources, **kw)
  File "/home/vitt/.virtualenvs/Topics/lib/python3.5/site-packages/nbconvert/exporters/templateexporter.py", line 295, in from_notebook_node
    output = self.template.render(nb=nb_copy, resources=resources)
  File "/home/vitt/.virtualenvs/Topics/lib/python3.5/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/home/vitt/.virtualenvs/Topics/lib/python3.5/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/vitt/.virtualenvs/Topics/lib/python3.5/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "<template>", line 119, in top-level template code
  File "/home/vitt/.virtualenvs/Topics/lib/python3.5/site-packages/nbconvert/exporters/../templates/rst.tpl", line 1, in top-level template code
    {%- extends 'display_priority.tpl' -%}
  File "/home/vitt/.virtualenvs/Topics/lib/python3.5/site-packages/nbconvert/exporters/../templates/skeleton/display_priority.tpl", line 1, in top-level template code
    {%- extends 'null.tpl' -%}
  File "/home/vitt/.virtualenvs/Topics/lib/python3.5/site-packages/nbconvert/exporters/../templates/skeleton/null.tpl", line 26, in top-level template code
    {%- block body -%}
  File "/home/vitt/.virtualenvs/Topics/lib/python3.5/site-packages/nbconvert/exporters/../templates/skeleton/null.tpl", line 28, in block "body"
    {%- block any_cell scoped -%}
  File "<template>", line 18, in block "any_cell"
  File "/home/vitt/.virtualenvs/Topics/lib/python3.5/site-packages/nbconvert/exporters/../templates/skeleton/null.tpl", line 31, in block "any_cell"
    {%- block codecell scoped -%}
  File "/home/vitt/.virtualenvs/Topics/lib/python3.5/site-packages/nbconvert/exporters/../templates/skeleton/null.tpl", line 41, in block "codecell"
    {%- block output_group -%}
  File "/home/vitt/.virtualenvs/Topics/lib/python3.5/site-packages/nbconvert/exporters/../templates/skeleton/null.tpl", line 45, in block "output_group"
    {%- block outputs scoped -%}
  File "/home/vitt/.virtualenvs/Topics/lib/python3.5/site-packages/nbconvert/exporters/../templates/skeleton/null.tpl", line 47, in block "outputs"
    {%- block output scoped -%}
  File "/home/vitt/.virtualenvs/Topics/lib/python3.5/site-packages/nbconvert/exporters/../templates/skeleton/null.tpl", line 61, in block "output"
    {%- block display_data scoped -%}
  File "<template>", line 140, in block "display_data"
  File "<template>", line 134, in block "nboutput"
  File "/home/vitt/.virtualenvs/Topics/lib/python3.5/site-packages/jinja2/runtime.py", line 553, in _invoke
    rv = self._func(*arguments)
  File "<template>", line 96, in template
  File "/usr/lib/python3.5/json/__init__.py", line 230, in dumps
    return _default_encoder.encode(obj)
  File "/usr/lib/python3.5/json/encoder.py", line 198, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.5/json/encoder.py", line 256, in iterencode
    return _iterencode(o, 0)
  File "/usr/lib/python3.5/json/encoder.py", line 179, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: Undefined is not JSON serializable
```

Debugging shows that "Undefined" is actually jinja2.runtime.Undefined with the following slots:

* _undefined_name: {str} 'application/javascript, application/vnd.bokehjs_load.v0+json'
* _undefined_obj: {NotebookNode} `{'application/javascript': '\n(function(root) {\n  function now() …`

Jinja Undefined represents _The default undefined type.  This undefined type can be printed and
    iterated over, but every other access will raise an :exc:`jinja2.exceptions.UndefinedError`_.

**Comment by thvitt** [comment]
There's https://github.com/spatialaudio/nbsphinx/issues/61 for bokeh + nbsphinx which is fixed in the nbsphinx version we use

**Comment by thvitt** [comment]
Possible next steps:

* prepare a minimal notebook that has a bokeh graph and run a stripped version through nbsphinx. Check if the problem exists. If it does, check whether our stripping does too much, and maybe ask nbsphinx or bokeh community for help. Otherwise, check what we do differently.
* check whether it really reproducably works with the non-stripped notebook (i.e. one that has been run through a browser once, not only using jupyter nbconvert --execute). If so, diff failing notebook with working version.

**Comment by thvitt** [comment]
Problem seems to occur with notebooks that have been running through the notebook GUI, as well :(
