### ISSUE TITLE
Mallet doctests fail in some situations

### ISSUE THREAD

**Issue by thvitt** [DARIAH-DE/Topics#45]
There are two mallet doctests that sometimes fail when I run them either using `pytest` in the checked-out project’s root directory, see the test output below.

I’ve also manually run the commands in the project root, and this also fails:

```python
In [1]: from dariah_topics.utils import Mallet
In [2]: tokenized_corpus = [['this','is','a','tokenized','document']]
In [3]: document_labels=['document_label']
In [4]: mallet = Mallet(corpus_output='.')
In [5]: mallet_corpus=mallet.import_tokenized_corpus(tokenized_corpus, document_labels)
[Same OSError about missing files as below]
```

Running the same code in an empty directory (with the same virtualenv) does work, and it produces the text file as well as the expected corpus.mallet.

I see multiple issues here:

1. the tests fail for no obvious reason
2. there is no message from mallet, not even an error message. Should not be. Should be logged as ERROR when mallet fails, or be part of the exception
3. the tests clutter the current (i.e. project) directory

As for 3., I think this simply should not be a doctest. Pytest has fixtures to provide a proper working directory, so we should write this as a proper test.

```
dariah_topics/utils.py:239 ([doctest] dariah_topics.utils.Mallet.import_tokenized_corpus)
279                 False.
280 
281         Returns:
282             The absolute path to the created MALLET corpus file.
283 
284         Example:
285             >>> tokenized_corpus = [['this', 'is', 'a', 'tokenized', 'document']]
286             >>> document_labels = ['document_label']
287             >>> mallet = Mallet(corpus_output='.')
288             >>> mallet_corpus = mallet.import_tokenized_corpus(tokenized_corpus, document_labels)
UNEXPECTED EXCEPTION: OSError('MALLET did not produce any output files. Maybe check your args?\nMissing files:\n - ./corpus.mallet\nPresent files: \n - \nWorking dir /home/tv/git/Topics',)
Traceback (most recent call last):

  File "/usr/lib/python3.6/doctest.py", line 1330, in __run
    compileflags, 1), test.globs)

  File "<doctest dariah_topics.utils.Mallet.import_tokenized_corpus[3]>", line 1, in <module>

  File "/home/tv/git/Topics/dariah_topics/utils.py", line 300, in import_tokenized_corpus
    _check_mallet_output(os.path.join(self.corpus_output, 'corpus.mallet'))

  File "/home/tv/git/Topics/dariah_topics/utils.py", line 163, in _check_mallet_output
    "\nWorking dir " + os.getcwd())

OSError: MALLET did not produce any output files. Maybe check your args?
Missing files:
 - ./corpus.mallet
Present files: 
 - 
Working dir /home/tv/git/Topics

/home/tv/git/Topics/dariah_topics/utils.py:288: UnexpectedException

dariah_topics/utils.py:304 ([doctest] dariah_topics.utils.Mallet.train_topics)
376             beta (float): Smoothing parameter for each topic-word. Defaults to 0.01.
377 
378         Returns:
379             None.
380 
381         Example:
382             >>> tokenized_corpus = [['this', 'is', 'a', 'tokenized', 'document']]
383             >>> document_labels = ['document_label']
384             >>> mallet = Mallet(corpus_output='.')
385             >>> mallet_corpus = mallet.import_tokenized_corpus(tokenized_corpus, document_labels)
UNEXPECTED EXCEPTION: OSError('MALLET did not produce any output files. Maybe check your args?\nMissing files:\n - ./corpus.mallet\nPresent files: \n - \nWorking dir /home/tv/git/Topics',)
Traceback (most recent call last):

  File "/usr/lib/python3.6/doctest.py", line 1330, in __run
    compileflags, 1), test.globs)

  File "<doctest dariah_topics.utils.Mallet.train_topics[3]>", line 1, in <module>

  File "/home/tv/git/Topics/dariah_topics/utils.py", line 300, in import_tokenized_corpus
    _check_mallet_output(os.path.join(self.corpus_output, 'corpus.mallet'))

  File "/home/tv/git/Topics/dariah_topics/utils.py", line 163, in _check_mallet_output
    "\nWorking dir " + os.getcwd())

OSError: MALLET did not produce any output files. Maybe check your args?
Missing files:
 - ./corpus.mallet
Present files: 
 - 
Working dir /home/tv/git/Topics

/home/tv/git/Topics/dariah_topics/utils.py:385: UnexpectedException

**Comment by thvitt** [comment]
Ah, now I see what happens: When I run `mallet import-dir --input . --output corpus.mallet`, I get an OutOfMemoryError after a while. Appearently, mallet tries to parse not only the files from the test but the whole working directory, probably including tox’ virtualenvs etc.

BTW `Mallet` class should log (debug level?) the exact command line it uses to call mallet in order to make debugging easier
