### ISSUE TITLE
not recognizing modeling library

### ISSUE THREAD

**Issue by saria85** [DARIAH-DE/Topics#63]
when I run through your example, it only recognizes preprocessing and not the other three library.
`from cophi_toolbox import preprocessing, modeling, postprocessing, visualization`
so here it can not recognizes these `modeling, postprocessing, visualization`
I have installed dariah....

anyone faced with this before?

**Comment by MHuberFaust** [comment]
it should be:
from cophi_toolbox import preprocessing
from dariah_topics import modeling, postprocessing, visualization

**Comment by saria85** [comment]
appreciate your prompt reply, It should be better if you edit your good example.
one more question, what it mean by `labels`.
My dataset does not have any label, it is a collection of txt files.
I appreciate that if you can let me know about this?

**Comment by severinsimmler** [comment]
This is indeed a typo in the README, thanks! (Will fix this).
A `label` is just the descriptor of one text. You could simply use the filenames for this. If you use e.g. `glob` to list your files

```python
>>> import glob
>>> path_to_corpus = "/home/user/corpus/*.txt"
>>> files = glob.glob(path_to_corpus)
>>> files
["/home/user/corpus/text1.txt", "/home/user/corpus/text2.txt"]
```
You could use `files` as `labels`, too.

If you really want to get started with topic modeling and this library, clone or download this repository, (install and) run [Jupyter](http://jupyter.org/), and check out the notebooks in the folder `notebooks`.

**Comment by saria85** [comment]
thanks, I have already listed the files, I did not know why the labels may be needed:) anyway many thanks.
I guess the example you put in the readme is not correct. 
I got this error
  File "/home/m193053/PycharmProjects/testi/tt.py", line 13, in <module>
    model = modeling.lda(topics=10, iterations=1000, implementation='mallet')
TypeError: lda() missing 1 required positional argument: 'document_term_matrix'

definitely I will go in depth, but I want to make sure it is applicable on my dataset.

**Comment by MHuberFaust** [comment]
we changed the data model significantly since we wrote the readme. Will be changed asap :)

**Comment by saria85** [comment]
Thanks :)

**Comment by saria85** [comment]
hi Michael,

Do you have the plan to update it during today or tomorrow?

Thanks for letting me know :)

**Comment by MHuberFaust** [comment]
I hope to fix it this afternoon. I will let you know as soon as it is done

**Comment by saria85** [comment]
sounds great

**Comment by MHuberFaust** [comment]
@saria85 switch to branch "testing" and try the Example of the README. It should work now.

Please let me know if it doesn't :)

**Comment by saria85** [comment]
I would appreciate if you can look at it, still raises error:

 File "/home/m193053/PycharmProjects/testi/tt.py", line 13, in <module>
    model = modeling.lda(topics=10, iterations=1000, implementation='mallet')
TypeError: lda() missing 1 required positional argument: 'document_term_matrix'

**Comment by saria85** [comment]
this is the whole error: Also I amrunning on IDE
 this is my code 👍 
```
from cophi_toolbox import preprocessing
from dariah_topics import modeling, postprocessing, visualization
import glob
pathlist = "/infodev1/phi-data/sohn/biobank/saria/biobank_65up_noCI_random_CN_cp/*.txt"
labels = glob.glob(pathlist)

corpus = preprocessing.read_files(pathlist)
tokens = [preprocessing.tokenize(document) for document in corpus]
matrix = preprocessing.create_document_term_matrix(tokens, labels)
stopwords = preprocessing.list_mfw(matrix)
clean_matrix = preprocessing.remove_features(stopwords, matrix)
vocabulary = clean_matrix.columns
model = modeling.lda(topics=10, iterations=1000, implementation='mallet')
topics = postprocessing.show_topics(model, vocabulary)
document_topics = postprocessing.show_document_topics(model, topics, labels)
PlotDocumentTopics = visualization.PlotDocumentTopics(document_topics)
static_heatmap = PlotDocumentTopics.static_heatmap().show()

```

```
/home/m193053/anaconda3/envs/conda3/bin/python3 /home/m193053/Downloads/Topics-master/test.py
ERROR cophi_toolbox.preprocessing: Skipping /, because the file format  is not supported.
ERROR cophi_toolbox.preprocessing: Skipping i, because the file format  is not supported.
ERROR cophi_toolbox.preprocessing: Skipping n, because the file format  is not supported.
ERROR cophi_toolbox.preprocessing: Skipping f, because the file format  is not supported.
ERROR cophi_toolbox.preprocessing: Skipping o, because the file format  is not supported.
ERROR cophi_toolbox.preprocessing: Skipping d, because the file format  is not supported.
ERROR cophi_toolbox.preprocessing: Skipping e, because the file format  is not supported.
ERROR cophi_toolbox.preprocessing: Skipping v, because the file format  is not supported.
ERROR cophi_toolbox.preprocessing: Skipping 1, because the file format  is not supported.
ERROR cophi_toolbox.preprocessing: Skipping /, because the file format  is not supported.
ERROR cophi_toolbox.preprocessing: Skipping p, because the file format  is not supported.
ERROR cophi_toolbox.preprocessing: Skipping h, because the file format  is not supported.
ERROR cophi_toolbox.preprocessing: Skipping i, because the file format  is not supported.
ERROR cophi_toolbox.preprocessing: Skipping -, because the file format  is not supported.
ERROR cophi_toolbox.preprocessing: Skipping d, because the file format  is not supported.
ERROR cophi_toolbox.preprocessing: Skipping a, because the file format  is not supported.
ERROR cophi_toolbox.preprocessing: Skipping t, because the file format  is not supported.
ERROR cophi_toolbox.preprocessing: Skipping a, because the file format  is not supported.
ERROR cophi_toolbox.preprocessing: Skipping /, because the file format  is not supported.
ERROR cophi_toolbox.preprocessing: Skipping s, because the file format  is not supported.
ERROR cophi_toolbox.preprocessing: Skipping o, because the file format  is not supported.
ERROR cophi_toolbox.preprocessing: Skipping h, because the file format  is not supported.
ERROR cophi_toolbox.preprocessing: Skipping n, because the file format  is not supported.
ERROR cophi_toolbox.preprocessing: Skipping /, because the file format  is not supported.
ERROR cophi_toolbox.preprocessing: Skipping b, because the file format  is not supported.
ERROR cophi_toolbox.preprocessing: Skipping i, because the file format  is not supported.
ERROR cophi_toolbox.preprocessing: Skipping o, because the file format  is not supported.
ERROR cophi_toolbox.preprocessing: Skipping b, because the file format  is not supported.
ERROR cophi_toolbox.preprocessing: Skipping a, because the file format  is not supported.
ERROR cophi_toolbox.preprocessing: Skipping n, because the file format  is not supported.
ERROR cophi_toolbox.preprocessing: Skipping k, because the file format  is not supported.
ERROR cophi_toolbox.preprocessing: Skipping /, because the file format  is not supported.
ERROR cophi_toolbox.preprocessing: Skipping s, because the file format  is not supported.
ERROR cophi_toolbox.preprocessing: Skipping a, because the file format  is not supported.
ERROR cophi_toolbox.preprocessing: Skipping r, because the file format  is not supported.
ERROR cophi_toolbox.preprocessing: Skipping i, because the file format  is not supported.
ERROR cophi_toolbox.preprocessing: Skipping a, because the file format  is not supported.
ERROR cophi_toolbox.preprocessing: Skipping /, because the file format  is not supported.
ERROR cophi_toolbox.preprocessing: Skipping b, because the file format  is not supported.
ERROR cophi_toolbox.preprocessing: Skipping i, because the file format  is not supported.
ERROR cophi_toolbox.preprocessing: Skipping o, because the file format  is not supported.
ERROR cophi_toolbox.preprocessing: Skipping b, because the file format  is not supported.
ERROR cophi_toolbox.preprocessing: Skipping a, because the file format  is not supported.
ERROR cophi_toolbox.preprocessing: Skipping n, because the file format  is not supported.
ERROR cophi_toolbox.preprocessing: Skipping k, because the file format  is not supported.
ERROR cophi_toolbox.preprocessing: Skipping _, because the file format  is not supported.
ERROR cophi_toolbox.preprocessing: Skipping 6, because the file format  is not supported.
ERROR cophi_toolbox.preprocessing: Skipping 5, because the file format  is not supported.
ERROR cophi_toolbox.preprocessing: Skipping u, because the file format  is not supported.
ERROR cophi_toolbox.preprocessing: Skipping p, because the file format  is not supported.
ERROR cophi_toolbox.preprocessing: Skipping _, because the file format  is not supported.
ERROR cophi_toolbox.preprocessing: Skipping n, because the file format  is not supported.
ERROR cophi_toolbox.preprocessing: Skipping o, because the file format  is not supported.
ERROR cophi_toolbox.preprocessing: Skipping C, because the file format  is not supported.
ERROR cophi_toolbox.preprocessing: Skipping I, because the file format  is not supported.
ERROR cophi_toolbox.preprocessing: Skipping _, because the file format  is not supported.
ERROR cophi_toolbox.preprocessing: Skipping r, because the file format  is not supported.
ERROR cophi_toolbox.preprocessing: Skipping a, because the file format  is not supported.
ERROR cophi_toolbox.preprocessing: Skipping n, because the file format  is not supported.
ERROR cophi_toolbox.preprocessing: Skipping d, because the file format  is not supported.
ERROR cophi_toolbox.preprocessing: Skipping o, because the file format  is not supported.
ERROR cophi_toolbox.preprocessing: Skipping m, because the file format  is not supported.
ERROR cophi_toolbox.preprocessing: Skipping _, because the file format  is not supported.
ERROR cophi_toolbox.preprocessing: Skipping C, because the file format  is not supported.
ERROR cophi_toolbox.preprocessing: Skipping N, because the file format  is not supported.
ERROR cophi_toolbox.preprocessing: Skipping _, because the file format  is not supported.
ERROR cophi_toolbox.preprocessing: Skipping c, because the file format  is not supported.
ERROR cophi_toolbox.preprocessing: Skipping p, because the file format  is not supported.
ERROR cophi_toolbox.preprocessing: Skipping /, because the file format  is not supported.
ERROR cophi_toolbox.preprocessing: Skipping *, because the file format  is not supported.
ERROR cophi_toolbox.preprocessing: Skipping ., because the file format  is not supported.
ERROR cophi_toolbox.preprocessing: Skipping t, because the file format  is not supported.
ERROR cophi_toolbox.preprocessing: Skipping x, because the file format  is not supported.
ERROR cophi_toolbox.preprocessing: Skipping t, because the file format  is not supported.
Traceback (most recent call last):
  File "/home/m193053/Downloads/Topics-master/test.py", line 13, in <module>
    model = modeling.lda(topics=10, iterations=1000, implementation='mallet')
TypeError: lda() missing 1 required positional argument: 'document_term_matrix'

```

**Comment by MHuberFaust** [comment]
you need to switch to the github branch "testing". 
[main page](https://github.com/DARIAH-DE/Topics)
in the top left side is a tab "branch: master" where you can switch to branch: testing. On this page the code is different :)

or just use this (copy pasted):
>>> from cophi_toolbox import preprocessing
>>> from dariah_topics import modeling, postprocessing, visualization
>>> pathlist = ['corpus/dickens_bleak.txt', 'corpus/thackeray_vanity.txt']
>>> labels = ['dickens_bleak', 'thackeray_vanity']
>>> corpus = preprocessing.read_files(pathlist)
>>> tokens = [preprocessing.tokenize(document) for document in corpus]
>>> matrix = preprocessing.create_document_term_matrix(tokens, labels)
>>> stopwords = preprocessing.list_mfw(matrix)
>>> clean_matrix = preprocessing.remove_features(stopwords, matrix)
>>> vocabulary = clean_matrix.columns
>>> model = modeling.lda(topics=10, iterations=1000, implementation='mallet')
>>> topics = postprocessing.show_topics(model, vocabulary)
>>> document_topics = postprocessing.show_document_topics(model, topics, labels)
>>> PlotDocumentTopics = visualization.PlotDocumentTopics(document_topics)
>>> PlotDocumentTopics.static_heatmap().show()

**Comment by saria85** [comment]
greatly appreciate your help. Its running know. :)
